export const MASTER_COA_LIST = [
  // --- A. PENERIMAAN ---
  { kode: "A11", nama: "Penerimaan dari Yayasan Lajnah", isHeader: false },
  { kode: "A121", nama: "Penerimaan SPP PAUD / RA / TPA", isHeader: false },
  { kode: "A122", nama: "Penerimaan SPP MI", isHeader: false },
  { kode: "A1231", nama: "Penerimaan SPP MTs Non Asrama", isHeader: false },
  { kode: "A1232", nama: "Penerimaan SPP MTs Asrama", isHeader: false },
  { kode: "A1233", nama: "Penerimaan SPP MA Non Asrama", isHeader: false },
  { kode: "A1234", nama: "Penerimaan SPP MA Asrama", isHeader: false },
  { kode: "A141", nama: "BOS MI", isHeader: false },
  { kode: "A142", nama: "BOS MTS", isHeader: false },
  { kode: "A143", nama: "BOS MA", isHeader: false },
  { kode: "A15", nama: "Penerimaan Usaha Pesantren (Laundry/Kantin/Parkir)", isHeader: false },
  { kode: "A171", nama: "Penerimaan kafalah dari Yayasan", isHeader: false },
  { kode: "A172", nama: "Penerimaan Kafalah dari nonyayasan", isHeader: false },
  { kode: "A19", nama: "ZIS", isHeader: false },
  { kode: "A21", nama: "Sumbangan (Keropak/Pemberian Langsung)", isHeader: false },
  { kode: "A22", nama: "Dana Amanah Pembangunan", isHeader: false },
  { kode: "A231", nama: "Wakaf Pengembangan / Bangunan", isHeader: false },
  { kode: "A232", nama: "Wakaf Perlengkapan Asrama", isHeader: false },
  { kode: "A2331", nama: "Perlengkapan Sekolah PAUD", isHeader: false },
  { kode: "A2332", nama: "Wakaf Perlengkapan Sekolah MTs dan MA", isHeader: false },
  { kode: "A2341", nama: "Buku dan Ujian MI", isHeader: false },
  { kode: "A2342", nama: "Buku dan Ujian MTs", isHeader: false },
  { kode: "A2343", nama: "Buku dan Ujian MA", isHeader: false },
  { kode: "A235", nama: "Biaya Kesehatan", isHeader: false },
  { kode: "A236", nama: "Biaya Bahan Seragam", isHeader: false },
  { kode: "A237", nama: "Seragam PAUD", isHeader: false },
  { kode: "A238", nama: "Dana Pengembangan Pesantren (DPP)", isHeader: false },
  { kode: "A2391", nama: "Perpustakaan MI", isHeader: false },
  { kode: "A2392", nama: "Perpustakaan MTs", isHeader: false },
  { kode: "A2393", nama: "Perpustakaan MA", isHeader: false },
  { kode: "A2401", nama: "Biaya Kegiatan MTs", isHeader: false },
  { kode: "A2402", nama: "Biaya Kegiatan MA", isHeader: false },
  { kode: "A241", nama: "Biaya Kegiatan PAUD / RA", isHeader: false },
  { kode: "A241_DU", nama: "Daftar Ulang Kenaikan Kelas", isHeader: false },
  { kode: "A242", nama: "Biaya Admin VA Sipond", isHeader: false },
  { kode: "A243", nama: "Biaya Pendaftaran PSB / Lomba", isHeader: false },
  { kode: "A24", nama: "Dana Titip (Donasi / Xendit Wallet)", isHeader: false },
  { kode: "A25", nama: "Piutang Guru & Karyawan", isHeader: false },
  { kode: "A26", nama: "Penerimaan Lain-lain / Tabungan Siswa", isHeader: false },

  // --- B. BEBAN OPERASIONAL ---
  { kode: "B11", nama: "Mukafaah Pegawai / PHL", isHeader: false },
  { kode: "B12", nama: "Sekretariat Mahad", isHeader: false },
  { kode: "B14", nama: "Kesantrian Banin", isHeader: false },
  { kode: "B15", nama: "Bidang Dakumsos", isHeader: false },
  { kode: "B16", nama: "Konsumsi Mahad", isHeader: false },
  { kode: "B17", nama: "Bidang Keuangan", isHeader: false },
  { kode: "B18", nama: "Bidang Rumah Tangga (RT)", isHeader: false },
  { kode: "B19", nama: "Bidang Usaha", isHeader: false },
  { kode: "B1101", nama: "Operasional PAUD", isHeader: false },
  { kode: "B1102", nama: "Operasional MI", isHeader: false },
  { kode: "B1103", nama: "Operasional MTS", isHeader: false },
  { kode: "B1104", nama: "Operasional MA", isHeader: false },
  { kode: "B111", nama: "Bea Tagihan Listrik", isHeader: false },
  { kode: "B112", nama: "Bea Telepon Dan Internet", isHeader: false },
  { kode: "B113", nama: "Bea Operasional Klinik", isHeader: false },
  { kode: "B115", nama: "Uang Muka / Kas Bon Operasional Rutin", isHeader: false },
  { kode: "B116", nama: "Bea Rutin Lainnya (Adm Bank)", isHeader: false },
  { kode: "B119", nama: "Kesantrian Putri (Banat)", isHeader: false },
  { kode: "B120", nama: "Bidang Multimedia", isHeader: false },
  { kode: "B21", nama: "Pelaksanaan Amanah Pembangunan", isHeader: false },
  { kode: "B22", nama: "Pelaksanaan Acara", isHeader: false },
  { kode: "B23", nama: "Piutang Guru & Karyawan", isHeader: false },
  { kode: "B24", nama: "Kas Bon Tidak Rutin", isHeader: false },
  { kode: "B29", nama: "Bea Tidak Rutin Lainnya", isHeader: false },
  { kode: "B311", nama: "Biaya Pendaftaran", isHeader: false },
  { kode: "B312", nama: "Wakaf Bangunan", isHeader: false },
  { kode: "B313", nama: "Wakaf Perlengkapan Asrama (Pengadaan)", isHeader: false },
  { kode: "B314", nama: "Wakaf Perlengkapan Sekolah (Pengadaan)", isHeader: false },
  { kode: "B151", nama: "Biaya Seragam PAUD", isHeader: false },
  { kode: "B152", nama: "Biaya Bahan Seragam MI MTs dan MA", isHeader: false },
  { kode: "B3161", nama: "Biaya Buku dan Ujian MI", isHeader: false },
  { kode: "B3162", nama: "Biaya Buku dan Ujian MTs", isHeader: false },
  { kode: "B3163", nama: "Biaya Buku dan Ujian MA", isHeader: false },
  { kode: "B3171", nama: "Biaya Kesehatan Pegawai", isHeader: false },
  { kode: "B3172", nama: "Biaya Kesehatan Santri", isHeader: false },
  { kode: "B3181", nama: "Biaya Perpustakaan MI", isHeader: false },
  { kode: "B3182", nama: "Biaya Perpustakaan MTS", isHeader: false },
  { kode: "B3183", nama: "Biaya Perpustakaan MA", isHeader: false },
  { kode: "B3191", nama: "Biaya Kegiatan MTS", isHeader: false },
  { kode: "B3192", nama: "Biaya Kegiatan MA", isHeader: false },
  { kode: "B320", nama: "Biaya DPP", isHeader: false },
  { kode: "B33", nama: "THT", isHeader: false }
];