export const POS_MAPPING = {
  "BIAYA PONDOKAN/SPP": { kode: "SPP_ROUTER", uraian: "Penerimaan SPP" },
  "WAKAF BANGUNAN": { kode: "A231", uraian: "Wakaf Pengembangan" },
  "PENDAFTARAN": { kode: "A243", uraian: "Pendaftaran PSB / Lomba" },
  "BIAYA KESEHATAN": { kode: "A235", uraian: "Kesehatan" },
  "DANA PENGEMBANGAN PESANTREN": { kode: "A238", uraian: "Dana Pengembangan Pesantren (DPP)" },
  "BIAYA DAFTAR ULANG": { kode: "A241_DU", uraian: "Daftar Ulang Kenaikan Kelas" },
  "BIAYA ADMINISTRASI": { kode: "A242", uraian: "Biaya admin VA Sipond" },
  "PENDAPATAN BIAYA ADMIN": { kode: "A242", uraian: "Biaya admin VA Sipond" },
  "SUMBANGAN YATIM": { kode: "A171", uraian: "Penerimaan kafalah dari Yayasan" },
  "KAFALAH YATIM": { kode: "A171", uraian: "Penerimaan kafalah dari Yayasan" },
  "SUMBANGAN DANA TPG": { kode: "A26", uraian: "Sumbangan Dana TPG" },
  "INFAK PROGRAM TPA": { kode: "A121", uraian: "Infaq Program TPA" },
  "HUTANG / PIUTANG": { kode: "A25", uraian: "Piutang Guru & Karyawan" },
  "LAIN-LAIN": { kode: "A26", uraian: "Penerimaan Lain-lain" },
  "PARKIR MOBIL": { kode: "A15", uraian: "Penerimaan Usaha Pesantren (Parkir)" },
  "HASIL USAHA PIT": { kode: "A15", uraian: "Penerimaan Usaha Pesantren" },
  "GUEST HOUSE": { kode: "A15", uraian: "Penerimaan Usaha Pesantren (Guest House)" },
  "LAUNDRY PAKAIAN": { kode: "A15", uraian: "Penerimaan Usaha Pesantren (Laundry)" },
  "KANTIN": { kode: "A15", uraian: "Penerimaan Usaha Pesantren (Kantin)" },
  "BIDAN PRAKTEK MANDIRI": { kode: "A15", uraian: "Penerimaan Usaha Pesantren (Bidan)" },
  "WAKAF PERLENGKAPAN ASRAMA": { kode: "A232", uraian: "Perlengkapan Asrama" },
  "WAKAF PERLENGKAPAN SEKOLAH": { kode: "A2332", uraian: "Perlengkapan Sekolah MTs dan MA" },
  "BIAYA BUKU / UJIAN PESANTREN": { kode: "A2342", uraian: "Buku dan Ujian MTs" },
  "BIAYA BAHAN SERAGAM": { kode: "A236", uraian: "Bahan Seragam" },
  "BIAYA BAHAN SERAGAM BATIK": { kode: "A236", uraian: "Bahan Seragam Batik" },
  "BIAYA SERAGAM": { kode: "A236", uraian: "Bahan Seragam" },
  "DANA BOS MI": { kode: "A141", uraian: "BOS MI" },
  "DANA BOS MTS": { kode: "A142", uraian: "BOS MTS" },
  "DANA BOS MA": { kode: "A143", uraian: "BOS MA" },
  "PUSTAKA IBNU TAIMIYAH": { kode: "A2392", uraian: "Perpustakaan MTs" },
  "BIAYA PERPUSTAKAAN": { kode: "A2392", uraian: "Perpustakaan MTs" },
  "EKSTRAKURIKULER": { kode: "A26", uraian: "Penerimaan Lain-lain (Ekskul)" },
  "BIAYA KEGIATAN RA": { kode: "A241", uraian: "Kegiatan PAUD" },
  "BIAYA KEGIATAN PAUD": { kode: "A241", uraian: "Kegiatan PAUD" },
  "BIAYA KEGIATAN MTS/MA": { kode: "A2401", uraian: "Kegiatan MTs" },
  "TABUNGAN SISWA": { kode: "A26", uraian: "Penerimaan Lain-lain (Tabungan Siswa)" },
  "DONASI KEMANUSIAAN": { kode: "A24", uraian: "Dana Titip (Donasi Kemanusiaan/Baksos)" },
  "DANA TITIPAN XENDIT": { kode: "A24", uraian: "Dana Titip (Xendit Wallet)" },
  "DANA TITIPAN IFTHOR": { kode: "A26", uraian: "Penerimaan Lain-lain (Ifthor)" }
};
